[profile.default]
solc_version = '0.8.20'
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_goerli = "${ARBITRUM_GOERLI_RPC_URL}"
59140 = "${LINEA_GOERLI_RPC}"

[etherscan]
168587773 = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/168587773/etherscan" }
59140 = { key = "X8Z1N5NIWGYIBZVW4RZXAGUI4HC4P9Z5SI", url = "https://goerli.lineascan.build/api" }